### ISSUE TITLE
Update requirement from Maven 3.3.9 to 3.5.0

### ISSUE THREAD

**Issue by khmarbaise** [pascalgn/properties-maven-extension#2]
In README you described to use at least Maven 3.3.9 which will not work with the placeholders correctly . You need Maven 3.5.0.

**Comment by pascalgn** [comment]
Thanks for the info. The bugs fixed in 3.5.0-beta-1 do not affect this extension, it is running fine with Maven 3.3.9. However, I have noted the 3.5.0-beta-1 release in the documentation.

**Comment by khmarbaise** [comment]
You haven't read the release notes not very carefully where for example [MNG-6057](https://issues.apache.org/jira/browse/MNG-6057) shows a different reactor order when you use properties for version tag...To be sure I would lift the requirement to 3.5.0-beta-1.

**Comment by pascalgn** [comment]
As I said, we already use it with Maven 3.3.9, so it's working just fine. The extension can also be used without version placeholders, for example to enable profiles based on the current branch. Maven 3.5.0 is not required.

**Comment by khmarbaise** [comment]
If you use properties the reactor changes in Maven 3.3.9 which is wrong. That's the point here...that you might use it with Maven 3.3.9 and have not yet problems is another story...
