### ISSUE TITLE
A new git commit count property

### ISSUE THREAD

**Issue by moleksyuk** [pascalgn/properties-maven-extension#3]
Hi @pascalgn,

Is it possible to have a new property that will return commit count to git repo? (`git rev-list HEAD --count`)

Thanks.

**Comment by pascalgn** [comment]
Sure! I released version 0.2.0 with the new property `git.count`, it should be in Maven Central in a few minutes.

**Comment by moleksyuk** [comment]
Thanks a lot @pascalgn 🆒
