### ISSUE TITLE
get directories

### ISSUE THREAD

**Issue by delanym** [pascalgn/properties-maven-extension#58]
I use the directory-maven-plugin to get the root directory of the reactor, which happens to be the repository workspace.

https://github.com/jdcasey/directory-maven-plugin#highest-basedir-goal

But due to the way plugins work, that execution runs in every project in the reactor, even though I only need it in the root project.

I could ask the author to provide an extension of his plugin, but I thought why not implement in this extension instead?

**Comment by pascalgn** [comment]
Good idea! I've added 2 new properties, git.dir.git and git.dir.worktree (see README) and released as 0.4.0 🚀 

(as usual, please allow some time until the Maven artifacts are available in the central repository, it usually takes a few hours)

Let me know if this works for you or if you have any other questions! 👍

**Comment by delanym** [comment]
Works like a charm. Thanks a lot.

**Comment by delanym** [comment]
@pascalgn any idea why the property isn't resolved in the <relativePath> tag?

```
      <parent>
        <groupId>com.eels</groupId>
        <artifactId>eels-maven-super</artifactId>
        <version>8.3.0</version>
        <relativePath>${git.dir.worktree}/pom.xml</relativePath>
      </parent>
```

**Comment by delanym** [comment]
When I print out the project properties with the antrun plugin
`<echoproperties destfile="${project.build.directory}/project.properties"/>`
I see the git.dir.worktree with its value there. But sometimes this property isn't being resolved. Like here:

`
      <plugin>
        <artifactId>maven-install-plugin</artifactId>
        <executions>
          <execution>
            <id>replace-extension-artefacts-with-endorsed</id>
            <phase>initialize</phase>
            <goals>
              <goal>install-file</goal>
            </goals>
            <configuration>
              <file>${git.dir.worktree}/provided/javax/inject/javax.inject/1/javax.inject-1.jar</file>
              <artifactId>javax.inject</artifactId>
              <groupId>javax.inject</groupId>
              <version>1</version>
              <packaging>jar</packaging>
              <generatePom>true</generatePom>
            </configuration>
          </execution>
        </executions>
      </plugin>
`

Is see in your integration test that you first make another property in the pom and assign it the value of the property provided by the extension.

https://github.com/pascalgn/properties-maven-extension/blob/5fc14bbc3b90a074656e9b3421fdd773eb5f3d61/src/it/check-git-properties/pom.xml#L41

Why is this necessary? I though the properties set by this extensions are made available to all projects and plugins?

**Comment by pascalgn** [comment]
This might be because the extension is not being run for some reason. When giving `-X` for debug output to mvn, do you see this line in the output?
```
[DEBUG] Using git repository: [...]/.git
```

**Comment by delanym** [comment]
No. I don't see logs for any extensions come to think of it. I added them recently, but only properties-maven-extension is required by Jenkins builds. This is the output just before Maven starts

> [service_BUILD] $ e:\java\jdk\jdk8u272-b10/bin/java -cp E:\java\jenkins\plugins\maven-plugin\WEB-INF\lib\maven35-agent-1.12.jar;E:\java\maven\apache-maven-3.6.3\boot\plexus-classworlds-2.6.0.jar;E:\java\maven\apache-maven-3.6.3/conf/logging jenkins.maven3.agent.Maven35Main E:\java\maven\apache-maven-3.6.3 E:\java\jenkins\war\WEB-INF\lib\remoting-3.28.jar E:\java\jenkins\plugins\maven-plugin\WEB-INF\lib\maven35-interceptor-1.12.jar E:\java\jenkins\plugins\maven-plugin\WEB-INF\lib\maven3-interceptor-commons-1.12.jar 51099^M
   22 <===[JENKINS REMOTING CAPACITY]===>^@^@^@channel started^M

**Comment by delanym** [comment]
I know the dependencies for the extensions are being downloaded because in the build itself we use an endorsed repository, and javax.inject is one of the artifacts. Your extension always overrides our endorsed artifact, so I have to work around that. So its getting that far at least!

**Comment by delanym** [comment]
It was this https://issues.jenkins.io/browse/JENKINS-30058
I worked around it using Maven wrapper.
