### ISSUE TITLE
Add git describe property

### ISSUE THREAD

**Issue by oskargit** [pascalgn/properties-maven-extension#6]
I have a need for the following git attributes:
- git.describe = gives the same output as the *git describe* command.
- git.closest.tag.name = the closest tag name
- git.closest.tag.commit.count = the closest commit count

I have already implemented the code and would like to push it up as a feature branch for review but I'm not allowed to create a branch in this project.

**Comment by pascalgn** [comment]
Hello @oskargit, thank you for the suggestions and ideas for contribution!

You cannot create a branch directly in this project, but you can go to https://github.com/pascalgn/properties-maven-extension and click "Fork" in the top right corner. This will create a copy of the repository under _your_ username, where you can push the desired changes. When you're done, create a merge request and we can have a look at the changes together!

For more info, take a look at this, for example: https://gist.github.com/Chaser324/ce0505fbed06b947d962
