### ISSUE TITLE
git tag incorrect

### ISSUE THREAD

**Issue by delanym** [pascalgn/properties-maven-extension#64]
Hi. Clearly no-one is using the git.tag.last property like I am.

The "last tag from sorted tag list (v1.2.3)" is not useful for builds, since it takes the latest tag, whether those tags apply to a commit on the branch or not.
In other words, currently, if I tag a commit on another branch, it will change the version number of my projects built on ALL OTHER BRANCHES. 

So instead of 

   git tag -l | tail -1

The behaviour should resemble

  git describe --abbrev=0

This will only show annotated tags, but I would prefer this as it allows developers to use normal tags for other things and leave the a-tags for version tagging.

**Comment by pascalgn** [comment]
Yes, good point. Do you want to provide a PR for this?

**Comment by delanym** [comment]
I'm afraid I've moved off this extension.

**Comment by certara-dneely** [comment]
It turns out we're trying to use 'git.last.tag' the same way and just encountered the same issue. We're trying to use the tags to defined the version, but the tag we get is not the most recent.  I've submitted a pull request with the modification I've found to work.

**Comment by certara-dneely** [comment]
I've changed the the code in my fork, restored git.tag.last and added git.describe.tag as a new property.

**Comment by certara-dneely** [comment]
Have you had a chance to look at my pull request to fix this issue?

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
